# Generated by Django 5.2.4 on 2025-08-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
