# Generated by Django 5.2.4 on 2025-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_type_alter_vehicletype_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
