# Generated by Django 5.2.4 on 2025-08-17 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
        ('vehicle', '0003_alter_vehicle_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
