# Generated by Django 5.2.4 on 2025-08-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0002_alter_sparepart_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='spareparttype',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='sparepart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spare_parts.sparepart'),
        ),
    ]
