# Generated by Django 5.2.4 on 2025-08-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0003_remove_attributevalue_spareparttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartimage',
            name='sparepart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparepatimages', to='spare_parts.sparepart'),
        ),
    ]
