# Generated by Django 5.2.4 on 2025-08-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0004_alter_sparepartimage_sparepart'),
        ('vehicle', '0003_alter_vehicle_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='vehicle.vehicle'),
        ),
    ]
